### 1️⃣ Guest Login (Create Guest Session)
POST http://localhost:3000/guest/login
Content-Type: application/json

GET http://localhost:3000/guest/validate
guest-id: {f256cb48-f8b5-4f75-aa8f-7f55dd43dbe4}

### 3️⃣ Logout Guest (Deletes session)
DELETE http://localhost:3000/guest/logout
guest-id: {f256cb48-f8b5-4f75-aa8f-7f55dd43dbe4}

### 4️⃣ Test Expired Guest Session (Wait 10 mins before running)
GET http://localhost:3000/guest-user/profile
guest-id: {58873d87-04c9-4327-b00c-ca4bfdf702bc}


